# Generated by Django 5.2.1 on 2025-05-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='1@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mot_de_passe',
            field=models.CharField(default='1111', max_length=100),
        ),
        migrations.AlterField(
            model_name='compte',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
